export const SECURITY_HEADERS = {
  "Content-Security-Policy": [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' https://analytics.egdata.app https://www.googletagmanager.com https://analytics.ahrefs.com https://static.cloudflareinsights.com chrome-extension: moz-extension:",
    "style-src 'self' 'unsafe-inline' https://cdn.egdata.app chrome-extension: moz-extension:",
    "img-src 'self' data: blob: https: chrome-extension: moz-extension:",
    "font-src 'self' data: https://cdn.egdata.app chrome-extension: moz-extension:",
    "connect-src 'self' https://api.egdata.app https://cdn.egdata.app https://pulse.egdata.app https://analytics.egdata.app https://kv.better-auth.com https://www.google-analytics.com https://*.analytics.google.com https://stats.g.doubleclick.net https://analytics.ahrefs.com https://cloudflareinsights.com chrome-extension: moz-extension:",
    "media-src 'self' https://cdn.egdata.app https://cdn1.epicgames.com https://media-cdn.epicgames.com",
    "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com",
    "worker-src 'self' blob:",
    "manifest-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ].join("; "),
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=(), interest-cohort=()",
} as const;
