ignoredBuiltDependencies:
  - es5-ext
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@sentry/profiling-node'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - prisma
  - workerd
overrides:
  solid-js: 1.9.9
  vite: npm:rolldown-vite@7.1.9
  '@better-auth/sso@<=1.6.0': 1.6.0
  workbox-build@<=7.4.1: 7.4.1
  nitropack@<=2.13.2: 2.13.2
  kysely@<=0.28.17: 0.28.17
  mongoose@<=8.22.1: 8.22.1
  mysql2@<=3.17.0: 3.17.0
  follow-redirects@<=1.16.0: 1.16.0
  prisma@<=7.6.0-dev.17: 7.6.0-dev.17
  lodash@<=4.17.23: 4.17.23
  better-auth@<=1.6.6: 1.6.6
  '@better-auth/core@<=1.6.6': 1.6.6
  rollup@<=3.29.5: 3.29.5
  import-in-the-middle@<=2.0.3: 2.0.3
  '@opentelemetry/instrumentation@<=0.207.0': 0.207.0
  hono@<=4.12.14: 4.12.14
  zod@<=4.4.0: 4.4.0
  cjs-module-lexer@<=2.2.0: 2.2.0
  undici@<=7.24.1: 7.24.1
