// Script to generate Hindi translation.json
// Run: node scripts/add-translation.mjs hi "common.appName" "EGDATA"
import { execSync } from "child_process";
import en from "../src/locales/en-US/translation.json" assert { type: "json" };

// Map of all translation keys to Hindi values
// Maintaining exact JSON structure as en-US
const HI_TRANSLATIONS = {
  "common.appName": "EGDATA",
  "common.search": "खोज",
  "common.searchPlaceholder": "गेम खोजें...",
  "common.loading": "लोड हो रहा है...",
  "common.free": "मुफ़्त",
  "common.notAvailable": "उपलब्ध नहीं",
  "common.cancel": "रद्द करें",
  "common.save": "सहेजें",
  "common.close": "बंद करें",
  "nav.toggleMenu": "नेविगेशन मेनू टॉगल करें",
  "nav.logoAlt": "EGDATA लोगो",
  "nav.explore": "एक्सप्लोर करें",
  "nav.browse": "ब्राउज़ करें",
  "nav.sales": "सेल",
  "nav.changelog": "बदलाव लॉग",
  "nav.about": "हमारे बारे में",
  "nav.rankings": "रैंकिंग",
  "nav.topSellers": "टॉप सेलर्स",
  "nav.mostPlayed": "सबसे ज़्यादा खेले गए",
  "nav.topWishlisted": "टॉप विशलिस्टेड",
  "nav.topNewReleases": "टॉप नए रिलीज़",
  "nav.seeAllCollections": "सभी कलेक्शन देखें",
  "nav.others": "अन्य",
  "nav.releaseStats": "रिलीज़ आँकड़े",
  "nav.genres": "शैलियाँ",
  "nav.seeAllGenres": "सभी शैलियाँ देखें",
  "nav.other": "अन्य",
  "nav.action": "एक्शन",
  "nav.rpg": "RPG",
  "nav.indie": "इंडी",
  "nav.strategy": "स्ट्रेटेजी",
  "nav.topSellerOnEpic": "Epic Games Store पर टॉप सेलर",
  "nav.searchItemTitle": "खोज",
  "nav.searchItemDesc": "Epic Games Store पर अपनी मनचाही चीज़ खोजें।",
  "nav.freeGamesItemTitle": "मुफ़्त गेम",
  "nav.freeGamesItemDesc": "Epic Games Store पर नवीनतम मुफ़्त गेम ऑफ़र देखें।",
  "nav.withDiscountsItemTitle": "छूट के साथ",
  "nav.withDiscountsItemDesc": "बड़ी छूट वाले गेम देखें।",
  "nav.helloUser": "नमस्ते, {{name}}!",
  "nav.dashboard": "डैशबोर्ड",
  "nav.logout": "लॉग आउट",
  "nav.searchLanguages": "भाषाएँ खोजें...",
  "nav.noLanguagesFound": "कोई भाषा नहीं मिली",
  "footer.logoAlt": "EGDATA लोगो",
  "footer.disclaimer": "एक फैन-निर्मित Epic Games Store डेटाबेस। Epic Games, Inc. से संबद्ध नहीं। सभी लोगो, छवियाँ और ट्रेडमार्क उनके संबंधित मालिकों के हैं।",
  "footer.legal": "कानूनी",
  "footer.privacyPolicy": "गोपनीयता नीति",
  "footer.notifications": "सूचनाएँ",
  "footer.resources": "संसाधन",
  "footer.apiDocs": "API दस्तावेज़",
  "footer.changelog": "बदलाव लॉग",
  "footer.community": "समुदाय",
  "footer.flagsByFlagpedia": "Flagpedia द्वारा झंडे",
  "footer.madeIn": "निर्मित",
  "meta.title": "Epic Games डेटाबेस - egdata.app",
  "meta.description": "व्यापक Epic Games Store डेटाबेस: गेम जानकारी, कीमतें, बिक्री इतिहास, फ़ाइल सूचियाँ, और बहुत कुछ। मुफ़्त गेम, आगामी रिलीज़ और सामुदायिक जानकारी देखें।",
  "meta.twitterTitle": "Epic Games डेटाबेस",
  "meta.twitterDescription": "एक मुफ़्त और ओपन-सोर्स Epic Games Store डेटाबेस जिसमें व्यापक गेम जानकारी, बिक्री ट्रैकिंग और बहुत कुछ है। सामुदायिक संचालित और लगातार अपडेट किया जाता है।",
  "meta.twitterImageAlt": "Epic Games डेटाबेस",
  "meta.ogTitle": "Epic Games डेटाबेस",
  "meta.ogDescription": "एक मुफ़्त और ओपन-सोर्स Epic Games Store डेटाबेस जिसमें व्यापक गेम जानकारी, बिक्री ट्रैकिंग और बहुत कुछ है। सामुदायिक संचालित और लगातार अपडेट किया जाता है।",
  "meta.ogImageAlt": "Epic Games डेटाबेस",
  "notFound.title": "पेज नहीं मिला",
  "home.statsBar.offersTracked": "ट्रैक किए गए ऑफ़र",
  "home.statsBar.priceChanges72h": "मूल्य परिवर्तन / 72 घंटे",
  "home.statsBar.activeDiscounts": "सक्रिय छूट",
  "home.statsBar.giveawaysToDate": "अब तक के गिवअवे",
  "home.sections.giveawayStats": "गिवअवे आँकड़े",
  "home.sections.giveawayOffers": "गिवअवे ऑफ़र",
  "home.sections.upcomingOffers": "आगामी ऑफ़र",
  "home.sections.latestOffers": "नवीनतम ऑफ़र",
  "home.sections.latestReleased": "नवीनतम रिलीज़",
  "home.sections.latestOffersWithAchievements": "उपलब्धियों वाले नवीनतम ऑफ़र",
  "home.sections.topSellingOffers": "टॉप-सेलिंग ऑफ़र",
  "home.sections.latestBuilds": "नवीनतम बिल्ड",
  "home.tableHeaders.hash": "#",
  "home.tableHeaders.pos": "स्था",
  "home.tableHeaders.dash": "-",
  "home.tableHeaders.title": "शीर्षक",
  "home.tableHeaders.starts": "शुरू",
  "home.tableHeaders.ends": "समाप्त",
  "home.tableHeaders.releaseDate": "रिलीज़ तारीख़",
  "home.tableHeaders.createdAt": "निर्माण तिथि",
  "home.tableHeaders.date": "तारीख़",
  "home.tableHeaders.price": "कीमत",
  "home.tableHeaders.size": "आकार",
  "home.tableHeaders.creationDate": "निर्माण तिथि",
  "home.offerHover.seller": "विक्रेता:",
  "home.offerHover.developer": "डेवलपर:",
  "home.offerHover.publisher": "प्रकाशक:",
  "home.offerHover.releaseDate": "रिलीज़ तारीख़:",
  "home.offerHover.ageRating": "आयु रेटिंग:",
  "home.offerHover.moreGenres_one": "+{{count}} और",
  "home.offerHover.moreGenres_other": "+{{count}} और",
  "home.offerHover.communityRating": "सामुदायिक रेटिंग:",
  "home.offerHover.igdbScore": "IGDB स्कोर",
  "home.offerHover.reviews": "• {{count}} समीक्षाएँ",
  "home.offerHover.timeToBeat": "पूरा करने का समय:",
  "home.offerHover.features": "विशेषताएँ:",
  "home.offerHover.moreFeatures": " +{{count}} और",
  "home.buildHover.unknownBuild": "अज्ञात बिल्ड",
  "home.buildHover.unknownDeveloper": "अज्ञात डेवलपर",
  "home.buildHover.size": "आकार",
  "home.buildHover.version": "संस्करण",
  "home.buildHover.created": "निर्मित",
  "home.buildHover.id": "ID: {{id}}",
  "home.multipleOffers": "{{title}} - एकाधिक ऑफ़र",
  "home.hero.subtitle": "कीमतों पर नज़र रखें, सौदे खोजें, और कोई भी मुफ़्त गेम मिस न करें। Epic Games Store डेटाबेस के लिए आपका साथी — ऑफ़र, छूट, गिवअवे, बिल्ड, और बहुत कुछ।",
  "home.hero.searchPlaceholder": "डेटाबेस खोजें…",
  "home.hero.justReleased": "अभी रिलीज़ हुआ",
  "home.hero.priceDrops72h": "मूल्य में गिरावट (72 घंटे)",
  "home.hero.hasAchievements": "उपलब्धियाँ हैं",
  "home.hero.upcoming": "आगामी",
  "home.hero.topSellers": "टॉप सेलर्स",
  "home.pulse.recentActivity": "हाल की गतिविधि",
  "home.pulse.badge.new": "नया",
  "home.pulse.badge.gone": "गया",
  "home.pulse.badge.offer": "ऑफ़र",
  "home.pulse.badge.build": "बिल्ड",
  "home.pulse.badge.item": "आइटम",
  "home.pulse.badge.asset": "एसेट",
  "home.pulse.badge.xp": "XP",
  "home.pulse.badge.sandbox": "सैंडबॉक्स",
  "home.pulse.badge.change": "परिवर्तन",
  "home.pulse.title.buildVersion": "बिल्ड {{version}}",
  "home.pulse.title.buildId": "बिल्ड {{id}}",
  "home.pulse.title.achievementsId": "उपलब्धियाँ {{id}}",
  "home.pulse.detail.newBuildIndexed": "नया बिल्ड इंडेक्स किया गया",
  "home.pulse.detail.buildManifestRefreshed": "बिल्ड मैनिफ़ेस्ट रिफ्रेश किया गया",
  "home.pulse.detail.achievementChanges_one": "{{count}} उपलब्धि {{entry}} {{verb}}",
  "home.pulse.detail.achievementChanges_other": "{{count}} उपलब्धियाँ {{entry}} {{verb}}",
  "home.pulse.detail.offerMetadataRefreshed": "ऑफ़र मेटाडेटा रिफ्रेश किया गया",
  "home.pulse.detail.fieldsChanged_one": "{{count}} फ़ील्ड {{verb}}",
  "home.pulse.detail.fieldsChanged_other": "{{count}} फ़ील्ड {{verb}}",
  "home.pulse.detail.fieldChanged": "{{field}} {{verb}}",
  "home.pulse.actionVerb.added": "जोड़ा गया",
  "home.pulse.actionVerb.removed": "हटाया गया",
  "home.pulse.actionVerb.updated": "अपडेट किया गया",
  "home.pulse.actionVerb.changed": "बदला गया",
  "home.pulse.entry_one": "प्रविष्टि",
  "home.pulse.entry_other": "प्रविष्टियाँ"
};

// ... (remaining translations would continue here)

// For now, write a note
console.log("This is a partial script. Full Hindi translations are available from the agent output.");
console.log("Use the following procedure:");
console.log("1. Read the en-US translation.json");
console.log("2. Translate each value to Hindi");
console.log("3. Write to src/locales/hi/translation.json");
